[package]
name = "show-changed-tests"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.20", features = ["derive"] }
gherkin = "0.14.0"
git2 = "0.19.0"

[dev-dependencies]
tempfile = "3.20.0"
