name: Release

on:
  push:
    tags:
      - '**[0-9]+.[0-9]+.[0-9]+*'

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ${{matrix.os.runner}}
    strategy:
      matrix:
        os:
        - name: Linux
          runner: ubuntu-latest
          artifact: "show-changed-tests"
        - name: Windows
          runner: windows-latest
          artifact: "show-changed-tests.exe"
        - name: MacOS
          runner: macOS-latest
          artifact: "show-changed-tests"
    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --release
    - name: Package
      run: |
        cd target/release/
        zip show-changed-tests-${{matrix.os.name}}.zip ${{matrix.os.artifact}}
    - uses: actions/upload-artifact@v4
      with:
        name: show-changed-tests-${{matrix.os.name}}
        path: target/release/show-changed-tests-${{matrix.os.name}}.zip
  publish:
    needs:
    - build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/download-artifact@v4
      with:
        pattern: show-changed-tests-*
        path: artifacts
        merge-multiple: true
    - uses: ncipollo/release-action@v1
      with:
        artifacts: artifacts/*
        body: ""
