name: Release

on:
  push:
    tags:
      - '**[0-9]+.[0-9]+.[0-9]+*'

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --release
    - uses: actions/upload-artifact@v4
      with:
        name: build-${{matrix.os}}
        path: target/release/show-changed-tests*
  publish:
    needs:
    - build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/download-artifact@v4
      with:
        pattern: build-*
        path: artifacts
        merge-multiple: true
    - uses: ncipollo/release-action@v1
      with:
        artifacts: artifacts/*
        body: ""
